config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#guide'

  resources :posts, path: 'berichten', only: [:show, :index]
  get '/feed' => 'posts#index', as: :feed, defaults: { format: :atom }

  get '/handboek' => 'static_pages#guide', as: :guide
  get '/afspraak' => 'appointments#new', as: :new_appointment

  get '/admin' => 'admin/posts#index', as: :admin
  namespace :admin do
    resources :posts
  end

  # Calendar
  get 'google_calendar' => redirect('https://www.google.com/calendar/embed?src=mo7vph6l2neh6m3bcju1ncon4k@group.calendar.google.com&ctz=Europe/Amsterdam'), as: :google_calendar
  get 'auth/google_oauth2/callback' => 'static_pages#callback'
end

app/models/event.rb
require 'google/api_client'

class Event
  include ActiveModel::Model
  attr_accessor :title, :starting_at, :ending_at

  def self.upcoming
    events = upcoming_events.map do |evt|
      regex = /FREQ=(?<rule>[^;]+)(;.+(?<interval>[0-9]+))?/
      opts = evt.key?('recurrence') ? evt['recurrence'].join.match(regex) : nil
      next nil if evt['start'].key?('date')
      new(
        starting_at: current_recurral(evt['start']['dateTime'], opts),
        ending_at: current_recurral(evt['end']['dateTime'], opts),
        title: evt['summary']
      )
    end

    events.delete_if(&:blank?).sort_by { |event| event.starting_at }
  end

  def self.upcoming_by_date
    obj = Hash.new { |hsh, key| hsh[key] = [] }

    hsh = upcoming.each_with_object(obj) do |event, events|
      events[event.starting_at.to_date] << event
    end

    Hash[hsh.sort_by { |date, _events| date }]
  end

  def self.client
    client = Google::APIClient.new(application_name: 'The Next Website')
    client.authorization.access_token = TNW::Google.access_token
    client
  end

  def self.upcoming_events
    starting_at = DateTime.now
    ending_at = starting_at.end_of_week

    tnw_calendar_id = Rails.application.secrets.google_calendar_id
    cal = client.discovered_api('calendar', 'v3')
    output = client.execute(api_method: cal.events.list,
                            parameters: {
                              'calendarId' => tnw_calendar_id,
                              'timeMin' => starting_at,
                              'timeMax' => ending_at
                            }
                           )

    JSON.parse(output.response.body)['items']
  end

  def self.current_recurral(date_time, opts)
    date_time = DateTime.parse(date_time)
    return date_time if opts.blank?

    this_week = (Date.today..Date.today + 1.week)
    interval = opts[:interval].blank? ? 1 : opts[:interval].to_i

    loop do
      rule = case opts[:rule]
             when 'WEEKLY' then :week
             end

      return date_time if this_week.include?(date_time.to_date)
      date_time += interval.send(rule)
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/tnw/google.rb
module TNW
  class Google
    include HTTParty
    base_uri 'https://accounts.google.com'

    def self.new_access_token
      options = {
        refresh_token: Rails.application.secrets.google_refresh_token,
        client_id: Rails.application.secrets.google_client_id,
        client_secret: Rails.application.secrets.google_client_secret,
        grant_type: 'refresh_token'
      }

      output = post('/o/oauth2/token', body: options)
      output.parsed_response['access_token']
    end

    def self.update_token!
      redis = Redis.new
      output = redis.set('tnw_google_access_token', new_access_token)
      redis.quit
      output == 'OK' ? true : fail
    end

    def self.access_token
      redis = Redis.new
      access_token = redis.get('tnw_google_access_token')
      redis.quit
      access_token
    end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < ApplicationController
    before_action :authenticate

    def index
      @posts = Post.order('created_at desc').all
    end

    def show
      @post = Post.find(params[:id])
    end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new post_params
      if @post.save
        redirect_to @post
      else
        render :new
      end
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit
      end
    end

    def destroy
      post = Post.find(params[:id])
      post.destroy
      redirect_to posts_path
    end

    private

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        if username == Rails.application.secrets.cms_username &&
           password == Rails.application.secrets.cms_password
          session[:logged_in] = true
        else
          false
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :upcoming_events_by_date, :current_week

  def logged_in?
    session.key?(:logged_in)
  end

  def upcoming_events_by_date
    @upcoming_events_by_date ||= Event.upcoming_by_date
  end

  def current_week
    (DateTime.now + 2.days).cweek
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :atom

  def index
    @posts = Post.order('created_at desc').all
    respond_with @posts
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
require 'open-uri'

class StaticPagesController < ApplicationController
  GUIDE_URL = 'https://raw.githubusercontent.com/NHLHogeschool/the-next-web/master/README.md'

  def guide
    # TODO: Add caching
    @title = 'Handboek'
    @body  = open(GUIDE_URL).read
    render :show
  end

  def callback
    render text: request.env['omniauth.auth'].to_hash.inspect
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(title)
    parts = ['The Next Web', title].delete_if(&:blank?)
    content_for :title, parts.join(': ')
  end

  def markdown(body)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
                                       autolink: true,
                                       tables: true)
    markdown.render(body).html_safe
  end
end

app/views/admin/posts/_form.haml
= form_for [:admin, post], html: { class: 'post-form' } do |f|
  %p= f.text_field :title
  %p= f.text_area :body, rows: 15
  %p
    = f.submit
    Nog
    %span.character-count 140
    karakters over voor een automatische tweet.

app/views/admin/posts/edit.html.haml
%h1 Bewerk bericht

= render 'form', post: @post

app/views/admin/posts/index.html.haml
%h1 Alle berichten

%p= link_to 'Nieuw bericht', new_admin_post_path

%table
  - for post in @posts
    %tr
      %td= link_to post.title, edit_admin_post_path(post)
      %td= l post.created_at, format: :short
      %td= link_to 'Verwijder', post, method: :delete

app/views/admin/posts/new.html.haml
%h1 Nieuw bericht

= render 'form', post: @post

app/views/appointments/new.html.haml
%h2= t('.title')

%p= t('.explanation')

#appointment-tool
  = t('.loading')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'Minor The Next Web'
    %link(href='//fonts.googleapis.com/css?family=Varela+Round:400' rel='stylesheet' type='text/css')
    %meta(name="viewport" content="width=device-width, initial-scale=1")

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = auto_discovery_link_tag :atom, feed_path

  %body
    %main
      = render 'shared/header'
      %section= yield
      %aside= render partial: 'shared/sidebar'
      = render 'shared/footer'

app/views/posts/_post.haml
%article
  %h1= link_to_unless params.key?(:id), post.title, post
  = markdown(post.body)

  - if logged_in?
    %p.admin-buttons
      = link_to 'Bewerk deze post', edit_admin_post_path(post)
      \-
      = link_to 'Verwijder deze post', [:admin, post], method: :delete

app/views/posts/index.html.haml
%h1= t('.title')

.post-list= render @posts

app/views/posts/show.html.haml
- title @post.title
.post= render 'post', post: @post

app/views/shared/_footer.haml
%footer
  %span
    Dit is een minor van de opleiding
    = link_to 'Communication & Multimedia Design', 'http://www.cmd-leeuwarden.nl'
    en niet gelieerd aan
    = link_to 'The Next Web', 'http://thenextweb.com'
    \.
  = link_to 'Beheer', admin_path

app/views/shared/_header.html.haml
%header
  %h1= link_to 'The Next Web', root_path

  %nav
    %ul
      %li.root= link_to 'Minor The Next Web', root_path
      %li.mobile-only= link_to t('.agenda'), '#agenda'
      %li= link_to t('.guide'), guide_path
      %li= link_to t('.appointment'), new_appointment_path

app/views/shared/_sidebar.haml
%h1
  %a(name='agenda')= t('.coming_week', week_number: current_week)

%table.event-list
  - if upcoming_events_by_date.blank?
    %p= t('.no_events')
  - else
    - upcoming_events_by_date.each do |date, events|
      %tr
        %th(colspan='2')
          - if date.today?
            = t('.today')
          - elsif date == Date.today.tomorrow
            = t('.tomorrow')
          - else
            = l(date, format: '%A').titleize
      - events.each do |event|
        %tr
          %td= l event.starting_at, format: '%H:%M'
          %td= event.title

%p= link_to t('.full_agenda'), google_calendar_path, target: '_blank'

app/views/static_pages/show.html.haml
= title @title
= markdown @body